web:
  build: .
  dockerfile: docker/web/Dockerfile
  command: nodemon index.js -w src
  working_dir: /app
  environment:
    PORT: 5000
    DB_NAME: example
    DB_USER: example
  volumes:
    - .:/app
  volumes_from:
    - node_modules
  ports:
    - 5000:5000
  links:
    - db

db:
  build: docker/db
  ports:
    - 5432:5432
